apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "claim1"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "63Gi"
  volumeName: "local-pv-21269d9f"
  storageClassName: "local-hdd"

